### ISSUE TITLE
How to use the linux build

### ISSUE THREAD

**Issue by YaBoiMax** [project-fika/Fika-ServerTools#5]
I copied the new linux build to where the old windows version was, but the server still looks for the .exe version
![error](https://github.com/user-attachments/assets/07cd4d05-9a83-4590-9967-1e45b1f15fc7)

**Comment by YaBoiMax** [comment]
Ok so I started the binary manually but it doesn't seem to be binding any ports
```
ss -tnlp

State                Recv-Q               Send-Q                             Local Address:Port                             Peer Address:Port              Process
LISTEN               0                    511                                      0.0.0.0:6969                                  0.0.0.0:*                  users:(("wineserver64",pid=38592,fd=329))
LISTEN               0                    4096                               127.0.0.53%lo:53                                    0.0.0.0:*                  users:(("systemd-resolve",pid=98,fd=14))
LISTEN               0                    100                                    127.0.0.1:25                                    0.0.0.0:*                  users:(("master",pid=299,fd=13))
LISTEN               0                    4096                                  127.0.0.54:53                                    0.0.0.0:*                  users:(("systemd-resolve",pid=98,fd=16))
LISTEN               0                    100                                        [::1]:25                                       [::]:*                  users:(("master",pid=299,fd=14))
LISTEN               0                    4096                                           *:22                                          *:*                  users:(("sshd",pid=126,fd=3),("systemd",pid=1,fd=40))
```

setting any other parameter also doesn't seem to work?
```
FikaServerTools -NatPunchServer -Port 6790

[B]Bind exception: System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at LiteNetLib.NetManager.BindSocket(Socket socket, IPEndPoint ep) in /home/runner/work/Fika-ServerTools/Fika-ServerTools/Networking/LiteNetLib/NetManager.Socket.cs:line 451, errorCode: AddressAlreadyInUse
NatPunchServer started on 0.0.0.0:0
```

**Comment by trippyone** [comment]
Try setting all the parameters. Example:

FikaServerTools -NatPunchServer -IP 0.0.0.0 -Port 6970 -NatIntroduceAmount 1

You can also try your public IP instead in the -IP parameter. Make sure to port forward 6970.
